on:
  pull_request:
    branches:
      - master
    types: [closed]

name: Add version tag

jobs:
  tag:
    name: Add version tag
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && github.event.pull_request.head.user.id == github.event.pull_request.base.user.id && startsWith(github.head_ref, 'release/')
    steps:
      - name: Get version
        uses: technote-space/get-next-version-action@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          EXCLUDE_MESSAGES: |
            update package version
            update packages
        if: "! startsWith(github.head_ref, 'release/v')"
      - name: Get version
        run: echo "::set-env name=NEXT_VERSION::${HEAD_REF#release/}"
        env:
          HEAD_REF: ${{ github.head_ref }}
        if: startsWith(github.head_ref, 'release/v')
      - uses: actions/github-script@0.4.0
        with:
          github-token: ${{ secrets.ACCESS_TOKEN }}
          script: |
            github.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: `refs/tags/${process.env.NEXT_VERSION}`,
              sha: context.sha
            })
        if: env.NEXT_VERSION
