on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - "!*"

name: CI

jobs:
  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    env:
      LINT: 1
    steps:
      - uses: actions/checkout@v2
      - uses: technote-space/get-git-comment-action@v1
      - uses: technote-space/get-diff-action@v1
        with:
          PREFIX_FILTER: |
            src/
            __tests__/
          SUFFIX_FILTER: .ts
          FILES: .eslintrc
        if: "! contains(env.COMMIT_MESSAGE, '[skip ci]') && ! contains(env.COMMIT_MESSAGE, '[ci skip]')"
      - name: Get Yarn Cache Directory
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
        if: env.GIT_DIFF
      - name: Cache node dependencies
        uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
        if: env.GIT_DIFF
      - name: Install Package dependencies
        run: yarn install
        if: env.GIT_DIFF
      - name: Check code style
        run: yarn eslint ${{ env.GIT_DIFF }}
        if: env.GIT_DIFF
      - uses: 8398a7/action-slack@v1
        with:
          type: failure
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: failure()

  jest:
    name: Jest
    needs: eslint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['10', '11', '12']
    steps:
      - uses: actions/checkout@v2
      - uses: technote-space/get-git-comment-action@v1
      - uses: technote-space/get-diff-action@v1
        with:
          PREFIX_FILTER: |
            src/
            __tests__/
          SUFFIX_FILTER: .ts
          FILES: |
            yarn.lock
            jest.config.js
        if: "! contains(env.COMMIT_MESSAGE, '[skip ci]') && ! contains(env.COMMIT_MESSAGE, '[ci skip]')"
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
        if: env.GIT_DIFF || github.event_name == 'push'
      - name: Get Yarn Cache Directory
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
        if: env.GIT_DIFF || github.event_name == 'push'
      - name: Cache node dependencies
        uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
        if: env.GIT_DIFF || github.event_name == 'push'
      - name: Install Package dependencies
        run: yarn install
        if: env.GIT_DIFF || github.event_name == 'push'
      - name: Run tests
        run: yarn cover
        if: env.GIT_DIFF || github.event_name == 'push'
      - name: Codecov
        run: |
          if [ -n "$CODECOV_TOKEN" ]; then
            curl -s https://codecov.io/bash | bash -s -- -t $CODECOV_TOKEN -f $COVERAGE_FILE
          fi
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
          COVERAGE_FILE: ./coverage/lcov.info
        if: matrix.node == '12' && (env.GIT_DIFF || github.event_name == 'push')
      - uses: 8398a7/action-slack@v1
        with:
          type: failure
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: failure()

  slack:
    name: Slack
    needs: jest
    runs-on: ubuntu-latest
    steps:
      - uses: 8398a7/action-slack@v1
        with:
          type: success
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
