on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - "!*"

name: Build

jobs:
  jest:
    name: Jest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 3
      - name: Install Package dependencies
        run: yarn install
      - name: Run tests
        run: yarn cover
      - name: Send covarage
        run: yarn add coveralls && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
          COVERALLS_SERVICE_NAME: "GitHub Action"
          COVERALLS_SERVICE_JOB_ID: ${{ github.sha }}
          COVERALLS_GIT_COMMIT: ${{ github.sha }}
          COVERALLS_GIT_BRANCH: ${{ github.ref }}
      - uses: 8398a7/action-slack@v1
        with:
          type: failure
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: failure()
      - uses: 8398a7/action-slack@v1
        with:
          type: success
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: success()
