on:
  issues:
    types: [opened]
name: Issue opened
jobs:
  assign:
    name: Assign issues to project
    runs-on: ubuntu-latest
    steps:
      - name: Assign issues to project
        uses: alex-page/github-project-automation-plus@v0.0.3
        with:
          project: Backlog
          column: To do
          repo-token: ${{ secrets.GITHUB_TOKEN }}

  assignAuthor:
    name: Assign author to issue
    runs-on: ubuntu-latest
    steps:
      - name: Assign author to issue
        uses: technote-space/assign-author@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
