on: issues
name: Issue opened
jobs:
  assign:
    name: Assign issues to project
    runs-on: ubuntu-latest
    steps:
      - name: Assign issues to project
        if: github.event.action == 'opened'
        uses: alex-page/add-new-issue-project@master
        with:
          args: "Backlog \"To do\""
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  assignAuthor:
    name: Assign author to issue
    runs-on: ubuntu-latest
    steps:
      - name: Assign author to issue
        if: github.event.action == 'opened'
        uses: technote-space/assign-author@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
