on: pull_request
name: Pull Request opened
jobs:
  assignToProject:
    name: Assign PullRequest to Project
    runs-on: ubuntu-latest
    steps:
      - name: Assign PullRequest to Project
        if: github.event.action == 'opened'
        uses: alex-page/github-project-automation-plus@master
        with:
          project: Backlog
          column: To do
          repo-token: ${{ secrets.GITHUB_TOKEN }}

  assignAuthor:
    name: Assign author to PR
    runs-on: ubuntu-latest
    steps:
      - name: Assign Author to PR
        if: github.event.action == 'opened'
        uses: technote-space/assign-author@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  addLabelsByBranch:
    name: PR Labeler
    runs-on: ubuntu-latest
    steps:
      - name: PR Labeler
        if: github.event.action == 'opened'
        uses: technote-fork/pr-labeler-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
