on:
  project_card:
    types: [moved]

name: Project Card Event

jobs:
  triage:
    name: Auto card labeler
    runs-on: ubuntu-latest
    steps:
      - name: Auto card labeler
        uses: technote-space/auto-card-labeler@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
