on: push
name: Push
jobs:
  assignAuthor:
    name: TOC Generator
    runs-on: ubuntu-latest
    steps:
      - name: TOC Generator
        uses: technote-space/toc-generator@v0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
