on:
  schedule:
    - cron: 0 14 * * 4
  repository_dispatch:
    types: [sync-workflows]

name: Sync workflows
jobs:
  release:
    name: Sync workflows
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Set variables
        run: |
          echo "::set-env name=MINUTE::$(echo "${GITHUB_REPOSITORY}" | md5sum | tr -d -c 0-9 | xargs -I{} echo {}123456789 | cut -c 2-9 | xargs -I{} bash -c 'echo $(({} % 60))')"
          echo "::set-env name=HOUR::$(echo "${GITHUB_REPOSITORY}" | md5sum | tr -d -c 0-9 | xargs -I{} echo {}123456789 | cut -c 2-9 | xargs -I{} bash -c 'echo $(({} % 24))')"
          echo "::set-env name=DAY::$(echo "${GITHUB_REPOSITORY}" | md5sum | tr -d -c 0-9 | xargs -I{} echo {}123456789 | cut -c 2-9 | xargs -I{} bash -c 'echo $(({} % 7))')"

      - name: Sync workflows
        uses: technote-space/create-pr-action@v2
        with:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          EXECUTE_COMMANDS: |
            rm -rdf .github/workflows/.tmp
            mkdir -p .github/workflows/.tmp
            git clone --depth=1 https://github.com/technote-space/github-actions-workflows.git .github/workflows/.tmp/workflows

            bash .github/workflows/.tmp/workflows/gh-actions/copy.sh
            sed -i "s/cron:.\+$/cron: ${MINUTE} ${HOUR} * * ${DAY}/" .github/workflows/update-dependencies.yml

            rm -rdf .github/workflows/.tmp
          COMMIT_MESSAGE: 'chore: sync workflows'
          PR_BRANCH_PREFIX: chore/
          PR_BRANCH_NAME: 'chore-sync-workflows'
          PR_TITLE: 'chore: sync workflows'
          ONLY_DEFAULT_BRANCH: true
