on:
  pull_request:
    types: [opened, synchronize, reopened, closed]

name: TOC Generator

jobs:
  toc:
    if: github.event.pull_request.head.user.id == github.event.pull_request.base.user.id
    name: TOC Generator
    runs-on: ubuntu-latest
    steps:
      - name: TOC Generator
        uses: technote-space/toc-generator@gh-actions
        with:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          TARGET_BRANCH_PREFIX: release/
          FOLDING: true
          MAX_HEADER_LEVEL: 3
          TOC_TITLE: Details
