on: push
name: TOC Generator
jobs:
  toc:
    name: TOC Generator
    runs-on: ubuntu-latest
    steps:
      - name: TOC Generator
        uses: technote-space/toc-generator@v1
        with:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
