on:
  schedule:
    - cron: 0 3 * * 2,6
  pull_request:
    types: [opened, reopened, closed]
  repository_dispatch:
    types: [update-deps]

name: Update dependencies
jobs:
  update:
    name: Update npm dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: technote-space/auto-cancel-redundant-job@v1
        with:
          EXCLUDE_MERGED: 'true'
      - name: Update dependencies
        id: update_deps
        uses: technote-space/create-pr-action@v1
        with:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          EXECUTE_COMMANDS: |
            npx npm-check-updates -u --packageFile package.json
            yarn install
            yarn upgrade
            yarn audit
          COMMIT_MESSAGE: 'chore: update npm dependencies'
          PR_BRANCH_NAME: 'chore-npm-update-${PR_ID}'
          PR_TITLE: 'chore: update npm dependencies (${PR_MERGE_REF})'
          PR_DEFAULT_BRANCH_PREFIX: release/
          PR_DEFAULT_BRANCH_NAME: next-${CURRENT_VERSION}
          PR_DEFAULT_BRANCH_TITLE: 'feat: release'
          TARGET_BRANCH_PREFIX: release/
          AUTO_MERGE_THRESHOLD_DAYS: 14

      - name: Set running flag
        run: echo "::set-env name=RUNNING::"
      - name: Set running flag
        run: echo "::set-env name=RUNNING::1"
        if: steps.update_deps.outputs.result != 'succeeded' && github.event_name == 'pull_request' && github.event.action != 'closed' && github.event.pull_request.head.user.id == github.event.pull_request.base.user.id && startsWith(github.head_ref, 'release/')
      - uses: actions/checkout@v2
        if: env.RUNNING
      - name: Set running flag
        run: |
          if [[ ! -f package.json ]] || [[ $(< package.json jq -r '.version == null') == 'true' ]]; then
            echo "::set-env name=RUNNING::"
          fi
      - name: Get version
        uses: technote-space/get-next-version-action@v1
        with:
          EXCLUDE_MESSAGES: |
            update package version
            update packages
        if: "env.RUNNING && ! startsWith(github.head_ref, 'release/v')"
      - name: Get version
        run: echo "::set-env name=NEXT_VERSION::${HEAD_REF#release/}"
        env:
          HEAD_REF: ${{ github.head_ref }}
        if: env.RUNNING && startsWith(github.head_ref, 'release/v')
      - name: Check package version
        uses: technote-space/package-version-check-action@v1
        with:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH_PREFIX: release/
          NEXT_VERSION: ${{ env.NEXT_VERSION }}
        if: env.NEXT_VERSION
